eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: post-service
          uri: http://localhost:8081
          predicates:
            - Path=/post/**
        - id: notification-service
          uri: http://localhost:8080
          predicates:
            - Path=/notification/**
